---
experiment:
    study_name: CaloDiT
    run_name:   check
    checkpoint_dir: ./checkpoint
    validation_dir: ./validation

gpu_info:
    use_gpu: True
    use_ddp: False

model_info:
    model_type: Diffusion       #generative frameworks: AE,MLE,VAE,GAN,Diffusion
    network_type: CaloDiT       #types of the neural network: Mixer, MixerTF, PatchTSMixer, MixBeast
    save_model: True            #save the itermediate models
    load_file: null             #path and file name of a trained network. 
    save_file: calodit.pt       #path and file name to save the trained model. 
                                #If null, the model is saved in chkeckpoint_dir using the default name
    gen_param:                  #paramters for generative framework
        diff_model: orig        #'orig' or 'rescaled'
        res_conn: True          #if True: y = x+f(x)
        dim_t_emb: 128          #dimension of positional embedding
        dim_c: 6                #dimension of conditioning variables (incl. geo)
        beta_info:              #diffusion scheduler info
            schedule: cosine
            num_steps: 200
            tau: 1
    network_param: #neural network specific parameter
        dim_r: 9
        dim_a: 16
        dim_v: 45
        dim_c: 256              #for Diffusion model dim_c should be always 2*dim_t_emb
        num_enc_layers: 2
        num_dec_layers: 2
        embed_dim: 144          #multiple of 3 and num_heads
        num_heads: 8
        mlp_ratio: 3
        patch_size: [3, 2, 3]
        variational: False      #Use Gaussian latent state or not

train_info:
    optimizer: Adam
    epochs: 2000
    learning_rate: 1.e-3
    batch_size: 128
    lr_scheduler:
        scheduler: scheduled  #either 'scheduled' or 'on_plateau'
        milestones: [10,20,40,80,160,320,640]
        gamma: 0.5
    save_freq: 20
    plot_freq: 20
    plot_config:
        - [70,  64, 'SiW']
        - [70, 128, 'SiW']
        - [70, 256, 'SiW']

data_info:
    dataloader: 'shower_dataset_2_all_cond'
    root_path: '/eos/user/p/praikwar/ddsim_out/Par04Flat/'
    valid_path: '/eos/geant4/fastSim/ddfastsim/Par04/dataset2_SiW_discrete/'
    geo: ["SiW"]
    angles: [70]
    energies: [64,128,256]
    data_split: [0.95,0.03,0.02]   #fractions of train, validation, test sets
    max_num_events: 100000

scale_info:
    scale_method: 'ds2_logit_trans_and_nomalization'  #data transformatin: lin_trans, log_trans, or bi-log_trans, ds2_logit_trans_and_nomalization
    scale_param:
        mean: -12.802077
        var: 2.076957
        epsilon_logit: 1.e-6
        scale_shower: 1.5
    scale_by_energy: True  #scale the data by incident energy
