---
experiment:
    study_name: PatchTS
    run_name:   fm_diffusion
    checkpoint_dir: /dccstor/kyeo_data/cern_fast_shower/chk_point
    validation_dir: /dccstor/kyeo_data/cern_fast_shower/validation

gpu_info:
    use_gpu: True
    use_ddp: False

model_info:
    model_type: Diffusion
    network_type: PatchTSMixer
    save_model: True
    load_file: null              #path and file name of a trained network.
    save_file: Diff_PatchTSM.pt  #path and file name to save the trained model.
                                 #If null, the model is saved in chkeckpoint_dir using the default name
    gen_param:
        diff_model: orig
        res_conn: False
        dim_t_emb: 32
        dim_c: 10
        beta_info:
            schedule: cos2
            num_steps: 400
        uniform_t: True
    network_param:
        dim_r: 9
        dim_a: 16
        dim_v: 45
        dim_c: 64 #2*dim_t_emb
    #PatchTST parameters
        patch_dim:   'r'          #patch dimension id: 'a', 'v', or 'r'  (azimuthal, vertical, ratidal)
        channel_dim: 'v'        #channel dimension id: 'a', 'v', or 'r'  (azimuthal, vertical, ratidal)
        d_model: 32
        decoder_d_model: 32
        reconstruction_head: True
        expansion_factor: 4
        num_layers: 1
        decoder_num_layers: 5
        dropout: 0.0
        head_dropout: 0.0
        #encoder compression
        d_model_layerwise_scale: [1]
        #decoder decompression
        decoder_d_model_layerwise_scale: [1,1,1,1,1]
        #
        use_positional_encoding: False
        variational: False
        #output_scale: 0.5
        #lower_bound: 0.0

train_info:
    optimizer: Adam
    epochs: 100000
    learning_rate: 1.e-3
    batch_size: 256
    lr_scheduler:
        scheduler: scheduled
        milestones: [500,1000,2000,4000,8000,16000,32000,64000]
        gamma: 0.5
    save_freq: 500
    plot_freq: 100
    plot_config:
        - [1.57, 0,  50, 'FCCeeALLEGRO']  #theta, phi, energy, geo
        - [1.57, 0,  50, 'FCCeeCLD'    ]  
        - [1.57, 0,  50, 'ODD'         ] 
        #- [1.57, 0,  50, 'Par04_PbWO4' ] 
        - [1.57, 0,  50, 'Par04_SciPb' ]
        - [1.57, 0,  50, 'Par04_SiW'   ]
        - [1.57, 0, 500, 'Par04_SiW'   ]

data_info:
    dataloader: 'shower_FM_dataset'

    train_path: ['/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/FCCeeALLEGRO/training',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/FCCeeCLD/training',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/ODD/training',
                 #'/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/Par04_PbWO4/training',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/Par04_SciPb/training',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/Par04_SiW/training']

    valid_path: ['/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/FCCeeALLEGRO/validation',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/FCCeeCLD/validation',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/ODD/validation',
                 #'/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/Par04_PbWO4/validation',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/Par04_SciPb/validation',
                 '/dccstor/tsfm23/datasets/CERN_Fast_Shower_Ver_2/Par04_SiW/validation']

    train_geo:  ['FCCeeALLEGRO','FCCeeCLD','ODD','Par04_SciPb','Par04_SiW']
    valid_geo:  ['FCCeeALLEGRO','FCCeeCLD','ODD','Par04_SciPb','Par04_SiW']

    random_geo_sampling: True
    num_samples_epoch: 25600

scale_info:
    scale_method: 'ds2_log_norm'  #data transformatin: lin_trans, log_trans, or bi-log_trans, ds2_log_norm
    scale_param:
        mean: -10.346238
        std: 3.644565
        epsilon_logit: 1.e-6
    scale_by_energy: False
